@startuml
title Time Deposit - Entity Relationship Diagram

hide circle
skinparam linetype ortho

entity "timeDeposits" as timeDeposits {
    * id : INTEGER <<PK>>
    --
    * plan_type : VARCHAR
    * days : INTEGER
    * balance : DECIMAL
}

entity "withdrawals" as withdrawals {
    * id : INTEGER <<PK>>
    --
    * time_deposit_id : INTEGER <<FK>>
    * amount : DECIMAL
    * date : DATE
}

timeDeposits ||--o{ withdrawals : has

@enduml